version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: algoritmo_local
    environment:
      POSTGRES_DB: algoritmo
      POSTGRES_USER: ToninhoEArthur
      POSTGRES_PASSWORD: ASenha
    ports:
      - "5432:5432"